package com.liuzhenli.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.liuzhenli.write.bean.WriteBook;
import com.liuzhenli.write.bean.WriteChapter;

import com.liuzhenli.greendao.WriteBookDao;
import com.liuzhenli.greendao.WriteChapterDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig writeBookDaoConfig;
    private final DaoConfig writeChapterDaoConfig;

    private final WriteBookDao writeBookDao;
    private final WriteChapterDao writeChapterDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        writeBookDaoConfig = daoConfigMap.get(WriteBookDao.class).clone();
        writeBookDaoConfig.initIdentityScope(type);

        writeChapterDaoConfig = daoConfigMap.get(WriteChapterDao.class).clone();
        writeChapterDaoConfig.initIdentityScope(type);

        writeBookDao = new WriteBookDao(writeBookDaoConfig, this);
        writeChapterDao = new WriteChapterDao(writeChapterDaoConfig, this);

        registerDao(WriteBook.class, writeBookDao);
        registerDao(WriteChapter.class, writeChapterDao);
    }
    
    public void clear() {
        writeBookDaoConfig.clearIdentityScope();
        writeChapterDaoConfig.clearIdentityScope();
    }

    public WriteBookDao getWriteBookDao() {
        return writeBookDao;
    }

    public WriteChapterDao getWriteChapterDao() {
        return writeChapterDao;
    }

}
