package com.liuzhenli.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.liuzhenli.write.bean.WriteBook;

import com.liuzhenli.greendao.WriteBookDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig writeBookDaoConfig;

    private final WriteBookDao writeBookDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        writeBookDaoConfig = daoConfigMap.get(WriteBookDao.class).clone();
        writeBookDaoConfig.initIdentityScope(type);

        writeBookDao = new WriteBookDao(writeBookDaoConfig, this);

        registerDao(WriteBook.class, writeBookDao);
    }
    
    public void clear() {
        writeBookDaoConfig.clearIdentityScope();
    }

    public WriteBookDao getWriteBookDao() {
        return writeBookDao;
    }

}
